[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  # Firebase environment variables will be set in the Netlify dashboard
  # FIREBASE_PROJECT_ID = "your-project-id"
  # FIREBASE_CLIENT_EMAIL = "your-client-email"
  # FIREBASE_PRIVATE_KEY = "your-private-key"

# First, handle API routes normally
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Then, handle all other routes with SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
