[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  # Firebase environment variables should be set in the Netlify dashboard as secrets

# First, handle API routes normally
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Then, handle all other routes with SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
